<?php
/**
 * @file
 * Adds a settings page and form
 */

/**
 * Implements hook_menu().
 */
function async_social_menu() {
	$items['admin/config/system/async_social'] = array(
		'title' 						=> t('Async Social Buttons With Counters'),
		'description' 			=> 'Select social networks and node types to attach social buttons with counters',
		'page callback' 		=> 'drupal_get_form',
		'page arguments'   	=> array('async_social_settings_form'),
		'access arguments'	=> array('administer site configuration'),
	);
	return $items;
}

/**
 * Implementation of hook_form_FORM_ID().
 */
function async_social_settings_form() {
	$form['async_social_links'] = array(
		'#type'          => 'checkboxes',
		'#title'         => t('Social Networks'),
		'#description'   => t('Display buttons for these social networks.'),
		'#default_value' => variable_get('async_social_links', array()),
		'#options'       => array('like' => 'Facebook Like', 'tweet' => 'Twitter Tweet', 'plusone' => 'Google +1'),
	);
	$form['async_social_nodetypes'] = array(
		'#type'          => 'checkboxes',
		'#title'         => t('Node types'),
		'#description'   => t('Display buttons for these node types.'),
		'#default_value' => variable_get('async_social_nodetypes', array()),
		'#options'       => node_type_get_names(),
	);
	return system_settings_form($form);
}

/**
 * Implementation of hook_node_view().
 */
function async_social_node_view($node, $view_mode) {
	$node_types = variable_get('async_social_nodetypes', array());
	$link_types = variable_get('async_social_links', array());
	$share_links = _async_social_links($node);

	foreach ($share_links as $key => $value) {
		if(isset($link_types[$key]) && !is_numeric($link_types[$key])) {
			$links_array[$key] = $share_links[$key];
		}
	}

	// Display in link section
	$show = (!empty($node->type) && in_array($node->type, $node_types, TRUE) && ($node->status == 1) && isset($links_array));  
	if ($show) {
		//$node->content['links']['async_social']['#markup'] = print theme('links', array('links' => $links_array));
		$node->content['links']['async_social'] = array(
			'#theme' => 'links',
			'#links' => $links_array,
			'#attributes' => array('class' => array('links', 'inline')),
		);
	}
}

// Helper function to create links
function _async_social_links($node) {
	$url = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => true));

	$facebook_share_url = 'http://www.facebook.com/sharer/sharer.php?u=' . $url;
	$twitter_share_url = 'http://twitter.com/intent/tweet?text=' . $node->title . ' ' . $url;
	$google_share_url = 'https://plus.google.com/share?url=' . $url;

	$links = array(
		'like'		=> array('title' => 'Facebook Like', 'href'	=> $facebook_share_url, 'attributes'	=> array('target' => '_blank'),),
		'tweet' 	=> array('title' => 'Twitter Tweet', 'href'	=> $twitter_share_url, 'attributes' 	=> array('target' => '_blank'),),
		'plusone'	=> array('title' => 'Google +1', 'href'			=> $google_share_url, 'attributes' 		=> array('target' => '_blank'),)
	);
	return $links;
}