<?php
/**
 * @file
 * Adds a settings page and form
 */

/**
 * Implements hook_menu().
 */
function async_social_menu() {
	$items['admin/config/system/async_social'] = array(
		'title' 						=> t('Async Social Buttons With Counters'),
		'description' 			=> 'Select social networks and node types to attach social buttons with counters',
		'page callback' 		=> 'drupal_get_form',
		'page arguments'   	=> array('async_social_settings_form'),
		'access arguments'	=> array('administer site configuration'),
	);
	return $items;
}

/**
 * Implements hook_form().
 */
function async_social_settings_form() {
	module_load_include('inc', 'async_social', 'langcodes');
	$form['async_social_buttons'] = array(
		'#type'          => 'checkboxes',
		'#title'         => t('Button types'),
		'#description'   => t('Display these buttons.'),
		'#default_value' => variable_get('async_social_buttons', array()),
		'#options'       => array('like' => 'Facebook Like', 'tweet' => 'Twitter Tweet', 'plusone' => 'Google +1')
	);
	$form['async_social_nodetypes'] = array(
		'#type'          => 'checkboxes',
		'#title'         => t('Node types'),
		'#description'   => t('Display buttons for these node types.'),
		'#default_value' => variable_get('async_social_nodetypes', array()),
		'#options'       => node_type_get_names()
	);
	$form['async_social_viewmodes'] = array(
		'#type'          => 'checkboxes',
		'#title'         => t('View modes'),
		'#description'   => t('Display buttons for these view modes.'),
		'#default_value' => variable_get('async_social_viewmodes', array()),
		'#options'       => _view_modes()
	);
	$form['async_social_langcode_facebook'] = array(
		'#type'          => 'select',
		'#title'         => t('Optional: Facebook Language'),
		'#description'   => t('Please choose a language for Facebook\'s button.<br />Will fall back to English if no language is chosen.'),
		'#default_value' => variable_get('async_social_langcode_facebook', array()),
		'#options'       => async_social_langcode_options('facebook')
	);
	$form['async_social_langcode_twitter'] = array(
		'#type'          => 'select',
		'#title'         => t('Optional: Twitter Language'),
		'#description'   => t('Please choose a language for Twitter\'s button.<br />Will fall back to English if no language is chosen.'),
		'#default_value' => variable_get('async_social_langcode_twitter', array()),
		'#options'       => async_social_langcode_options('twitter')
	);
	$form['async_social_langcode_google'] = array(
		'#type'          => 'select',
		'#title'         => t('Optional: Google Language'),
		'#description'   => t('Please choose a language for Google\'s button.<br />Will fall back to English if no language is chosen.'),
		'#default_value' => variable_get('async_social_langcode_google', array()),
		'#options'       => async_social_langcode_options('google')
	);
	$form['async_social_facebook_appid'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Optional: Facebook AppID'),
		'#description'   => t('Enter a Facebook AppID if you have one. It\'s not necessary to make the button work.<br />You only need it for tracking and customised button actions within your Facebook page.'),
		'#default_value' => variable_get('async_social_facebook_appid', array()),
	);
	return system_settings_form($form);
}

/**
 * Implements hook_node_view().
 */
function async_social_node_view($node, $view_mode) {
	// first look for matching node types and view modes
	$node_types = variable_get('async_social_nodetypes', array());
	$view_modes = variable_get('async_social_viewmodes', array());
	if (in_array($node->type, $node_types, TRUE) && in_array($view_mode, $view_modes, TRUE)) {
		// and create the new region
		$node->content['async_social'] = array(
			'#prefix' => '<div id="async-social-buttons">',
			'#suffix' => '</div>'
		);
		// then look for chosen button types and prepare buttons
		$button_types = variable_get('async_social_buttons', array());
		$buttons = _async_social_buttons($node);
		foreach ($button_types as $key => $value) {
			// and finally add them
			if($key === $value) {
				$node->content['async_social'][$key] = array(
					'#markup' => $buttons[$key],
					'#prefix' => '<div class="' . $key . ' async-social-button">',
					'#suffix' => '</div>'
				);
			}
		}
	}
	// $default_theme = variable_get('theme_default', NULL);
	// $regions = system_region_list($default_theme, REGIONS_ALL);
}

/**
 * Implements hook_page_build().
 */
function async_social_page_build(&$page) {

	$google_lang = variable_get('async_social_langcode_google', 'en-US');
	$google_script = "window.___gcfg = {
		lang: '" . $google_lang . "'};
		(function() {
			var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			po.src = 'https://apis.google.com/js/plusone.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		})();";
  drupal_add_js($google_script, array(
    'type'	=> 'inline',
    'scope'	=> 'footer'
  ));

  $twitter_script = 'window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return t;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));';
  drupal_add_js($twitter_script, array(
    'type'	=> 'inline',
    'scope' => 'footer'
  ));

  $facebook_lang = variable_get('async_social_langcode_facebook', 'en_US');
  $facebook_appid = variable_get('async_social_facebook_appid', '');
  $facebook_appid = !empty($facebook_appid) ? '&appId=' . $facebook_appid : '';
  $facebook_script = '(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.async = true; js.src = "//connect.facebook.net/' . $facebook_lang . '/sdk.js#xfbml=1&version=v2.3' . $facebook_appid . '";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, \'script\', \'facebook-jssdk\'));';
	drupal_add_js($facebook_script, array(
    'type' => 'inline',
    'scope' => 'footer'
  ));

  drupal_add_css(drupal_get_path('module', 'async_social') . '/css/async_social.css');
}

/**
 * Helper function to create buttons markup
 * @param  object $node the node object
 * @return array $buttons array to build markup on node view
 */
function _async_social_buttons($node) {
	$url = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => true));

	$twitter_lang = variable_get('async_social_langcode_twitter', 'en');
	$twitter_lang = ($twitter_lang != 'en') ? ' data-lang="' . $twitter_lang . '"' : '';
	$buttons = array(
		'like'		=> '<div class="fb-like" data-href="' . $url . '" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>',
		// TO DO set data-via attribute https://dev.twitter.com/web/tweet-button
		'tweet' 	=> '<a class="twitter-share-button" href="https://twitter.com/share"' . $twitter_lang . ' data-url="' . $url . '" data-text="' . $node->title . '">Tweet</a>',
		'plusone'	=> '<g:plusone callback="plusone_vote" size="medium" href="' . $url . '"></g:plusone>'
	);
	return $buttons;
}

/**
 * Helper function to build select list options for view modes
 * @return array $view_modes array of all available view modes
 */
function _view_modes() {
	$entity_info = entity_get_info('node');
	$view_modes = array();
	foreach ($entity_info['view modes'] as $machine_name => $property) {
		$view_modes[$machine_name] = $property['label'];
	}
	return $view_modes;
}